// Mocks generated by Mockito 5.4.5 from annotations
// in event_planner/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:event_planner/provider/auth_provider.dart' as _i3;
import 'package:image_picker/image_picker.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:shared_preferences/shared_preferences.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedPreferences_0 extends _i1.SmartFake
    implements _i2.SharedPreferences {
  _FakeSharedPreferences_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthenticationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationProvider extends _i1.Mock
    implements _i3.AuthenticationProvider {
  MockAuthenticationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedPreferences get prefs =>
      (super.noSuchMethod(
            Invocation.getter(#prefs),
            returnValue: _FakeSharedPreferences_0(
              this,
              Invocation.getter(#prefs),
            ),
          )
          as _i2.SharedPreferences);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isUploading =>
      (super.noSuchMethod(Invocation.getter(#isUploading), returnValue: false)
          as bool);

  @override
  bool get canResend =>
      (super.noSuchMethod(Invocation.getter(#canResend), returnValue: false)
          as bool);

  @override
  bool get hasChanged =>
      (super.noSuchMethod(Invocation.getter(#hasChanged), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void onChange({bool? val = true}) => super.noSuchMethod(
    Invocation.method(#onChange, [], {#val: val}),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signUp(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [email, password]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearMessages() => super.noSuchMethod(
    Invocation.method(#clearMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> createUpdateUserData({
    required String? firstName,
    required String? lastName,
    required String? email,
    required String? phoneNumber,
    required String? mailingAddress,
    required String? profileImageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUpdateUserData, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #phoneNumber: phoneNumber,
              #mailingAddress: mailingAddress,
              #profileImageUrl: profileImageUrl,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> checkUserAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#checkUserAvailable, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void listenToUserData() => super.noSuchMethod(
    Invocation.method(#listenToUserData, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> selectImage(_i5.ImageSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#selectImage, [source]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> uploadProfileImage() =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> saveUserData() =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String> getFcmToken() =>
      (super.noSuchMethod(
            Invocation.method(#getFcmToken, []),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(this, Invocation.method(#getFcmToken, [])),
            ),
          )
          as _i4.Future<String>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
