name: event_planner
description: Practical test for swivel - gayan sirimanna - ATL

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get_it: ^8.0.3
  shared_preferences: ^2.0.15
  fluro: ^2.0.4
  flutter_svg_provider: ^1.0.3
  flutter_svg: ^2.0.17
  provider: ^6.1.2
  easy_localization: ^3.0.1
  sizer: ^2.0.15
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3
  dio: ^5.8.0+1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/translations/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
