// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG4WOS7dYf-yY1qcffGKTM5V21NCjjWx4',
    appId: '1:350782808185:web:dfe01df11d4749093df4a8',
    messagingSenderId: '350782808185',
    projectId: 'event-planner-143b0',
    authDomain: 'event-planner-143b0.firebaseapp.com',
    storageBucket: 'event-planner-143b0.firebasestorage.app',
    measurementId: 'G-FBFY9R85RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT1LcpEV7vQVeOMYYi0UOWQqozQdVc0EU',
    appId: '1:350782808185:android:2b21f84fea70b4d23df4a8',
    messagingSenderId: '350782808185',
    projectId: 'event-planner-143b0',
    storageBucket: 'event-planner-143b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Zx7c8N7SGnOL7sOj4YzAxG155zE0MVI',
    appId: '1:350782808185:ios:3b45d4426f80c8923df4a8',
    messagingSenderId: '350782808185',
    projectId: 'event-planner-143b0',
    storageBucket: 'event-planner-143b0.firebasestorage.app',
    iosBundleId: 'com.gayan.eventplanner',
  );

}